# Responsibility: Rank the engines that can take a geometry by how they did, in the lab, on shapes measured to be like it.
# Owns: the shape classes (from measured traits), the committed fitness table's reading, the ranking and its plain-words reasons.
# Boundaries: advice only - it never selects, refuses or switches an engine; the capability filter decides who CAN, the user picks.
# Collaborates with: cad/shape_traits.py (the measurements), engines/fitness_table.json (the evidence, written by
#                    devtools/fitness/build_engine_fitness.py), engines/capability.py, agents/intake/, pipeline/engine_fallback.py.
"""WHICH ENGINE IS BEST FOR THIS SHAPE - measured, explained, and never imposed.

The capability filter (engines/capability.py) answers which engines CAN mesh a file for a flow.
This module answers which of those is likely BEST for this particular geometry, and why, from
evidence: every lab run of every engine on the production mesh image, each geometry measured with
the same shape traits (cad/shape_traits.py) a user's upload is measured with. The user always
picks; this is the recommendation they pick from.

THE MODEL is a table, not a black box. Each lab run is one row: the measured traits of its
geometry, the engine, the file's form and what happened (passed or not, layer coverage, cells,
time). A new geometry is put in a SHAPE CLASS by its traits:

    internal  tube        one passage, about as wide as its openings, long against its width
              branched    the same, with three or more openings
              chamber     much wider than its openings, or short and stubby
              thin gap    a gap or annulus: the passage spans half its openings' hydraulic diameter
              obstacles   a passage round many internal obstacles - a tube bank (three or more
                          handles through the fluid)
    external  thin body   under a quarter as thick across the flow as it is long (wings, blades)
              thick body  thicker (cars, nacelles, cylinders, discs facing the flow)
              + detailed  several bodies, an open or non-manifold surface, or dense sharp edges
    multi-region          fluid and solid regions together

For each engine the evidence is read at four levels, most specific first: the same class from the
same kind of file, the same class from any file, the same flow from the same kind of file, the same
flow. Its pass rate is read from the most specific level that has runs, plus two pseudo runs at the
rate of the next broader group that has more, so a few runs on shapes exactly like this count, but
only as much as a few runs can.
Engines rank by a CAUTIOUS score - that rate less one standard error of it - so an engine with a
long record on shapes like this outranks one that was never tried on them (whose record on other
kinds of shape is halved toward even odds and weighs no more than the pseudo runs), and three
passes out of three never outrank thirty out of thirty-two. Scores within 5% tie; then measured layer
coverage, then time decide. Every number in a reason is a count of real runs; thin evidence says
so.

Engines may also DECLARE where they are at home (EngineSpec.home_turf, rows of a fact, a test, a
severity and words). Those rows give the plain "why"; an OUTSIDE row keeps an engine from being
recommended - it stays on the list, marked, for the user to pick if they want it. The ranking
itself comes only from measured runs.
"""
from __future__ import annotations

import json
import logging
import math
import statistics
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Any

from meshpipeline.cad.shape_traits import TRAITS_VERSION, ShapeTraits

logger = logging.getLogger(__name__)

#: The committed evidence. Regenerated by devtools/fitness/build_engine_fitness.py.
TABLE_PATH = Path(__file__).with_name("fitness_table.json")

#: An evidence level is used once it holds runs on at least this many distinct shapes.
MIN_SHAPES = 3
#: Pass rates are shrunk toward the next broader group's rate by this many pseudo runs.
PRIOR_RUNS = 2.0
#: The score is the rate less this many standard errors of it (a cautious estimate).
CAUTION = 1.0
#: Rates closer than this rank as a tie (then layers, then time decide).
TIE_STEP = 0.05
#: What a mesh WITHOUT reliable near-wall layers is worth, against one with them, when the brief
#: asks for layers: an engine that declares none (EngineSpec.delivered_mesh.prism_layers) has its
#: measured rate scaled by this. Its mesh is not quite the one asked for - the fallback ladder
#: offers such an engine and never swaps a run onto it (pipeline/engine_fallback.py).
NO_LAYERS_VALUE = 0.7

# the shape classes
TUBE = "tube"
BRANCHED = "branched"
CHAMBER = "chamber"
THIN_GAP = "thin gap"
OBSTACLES = "obstacles"
SLENDER = "thin body"
BLUNT = "thick body"
MULTI_REGION = "multi-region"

#: gap_vs_port bands (shared with VMTK's declared turf): a round passage reads ~1, a gap ~0.5.
GAP_THIN_BELOW = 0.6
CHAMBER_ABOVE = 1.4
#: wetted area / (pi * chord^2) under this is short and stubby
STUBBY_BELOW = 3.0
#: handles through the fluid at or above this read as a tube bank
OBSTACLES_FROM = 3
#: smallest cross-flow extent / streamwise extent at or above this is a thick body
BLUNT_FROM = 0.25
#: feature-edge length per sqrt(area) above this is a detailed body
DETAILED_EDGES = 12.0

_CLASS_WORDS: dict[str, str] = {
    TUBE: "long passages about as wide as their openings",
    BRANCHED: "branching passages about as wide as their openings",
    CHAMBER: "chambers much wider than their openings",
    THIN_GAP: "thin gaps or annuli",
    OBSTACLES: "passages around many internal obstacles, like a tube bank",
    SLENDER: "thin bodies in external flow",
    BLUNT: "thick bodies in external flow",
    MULTI_REGION: "multi-region fluid and solid assemblies",
}
_ONE_SHAPE_WORDS: dict[str, str] = {
    TUBE: "a long passage about as wide as its openings",
    BRANCHED: "branching passages about as wide as their openings",
    CHAMBER: "a chamber much wider than its openings",
    THIN_GAP: "a thin gap or annulus",
    OBSTACLES: "a passage around many internal obstacles, like a tube bank",
    SLENDER: "a thin body in external flow",
    BLUNT: "a thick body in external flow",
    MULTI_REGION: "a multi-region fluid and solid assembly",
}
_FLOW_WORDS = {"internal": "internal-flow shapes", "external": "external bodies",
               "multi-region": "multi-region assemblies", "structural": "structural parts"}
_FORM_WORDS = {"cad": "from CAD", "surface": "from surface meshes"}


# #
# the shape class, from measured traits
# #

def handles_through_fluid(t: ShapeTraits) -> int | None:
    """Handles of the surface that cross the FLUID: all of them for a fluid-domain solid; for a
    wall around the fluid, those beyond the ones its own openings make (a tee's wall has two)."""
    if t.genus is None:
        return None
    if t.flow == "internal" and t.input_kind not in ("", "fluid-domain"):
        return max(0, t.genus - max((t.ports or 0) - 1, 0))
    return t.genus


def is_detailed(t: ShapeTraits) -> bool:
    return bool(t.n_solids > 1 or t.closed is False
                or (t.sharp_edges is not None and t.sharp_edges > DETAILED_EDGES))


def shape_class(t: ShapeTraits) -> str:
    """The class of a measured geometry ('' when the traits cannot place it)."""
    if t.flow == "multi-region":
        return MULTI_REGION
    if t.flow == "external":
        if t.thickness_ratio is None:
            return ""
        return BLUNT if t.thickness_ratio >= BLUNT_FROM else SLENDER
    if t.flow != "internal":
        return ""
    handles = handles_through_fluid(t)
    if handles is not None and handles >= OBSTACLES_FROM:
        return OBSTACLES
    g, s = t.gap_vs_port, t.slenderness
    if g is None and s is None:
        return ""
    if g is not None and g < GAP_THIN_BELOW:
        return THIN_GAP
    if (g is not None and g > CHAMBER_ABOVE) or (s is not None and s < STUBBY_BELOW):
        return CHAMBER
    return BRANCHED if (t.ports or 0) >= 3 else TUBE


def shape_words(t: ShapeTraits) -> str:
    """The shape in a few plain words, e.g. 'a thin gap or annulus' ('' when unplaced)."""
    c = shape_class(t)
    words = _ONE_SHAPE_WORDS.get(c, "")
    if words and t.flow == "external" and is_detailed(t):
        words += ", with fine detail"
    return words


def _levels(flow: str, cls: str, form: str) -> list[tuple[tuple[str, str, str], str]]:
    """The evidence levels, most specific first: (key, plain words for 'similar shapes')."""
    out = []
    if cls and form:
        out.append(((flow, cls, form), f"{_CLASS_WORDS.get(cls, cls)}, {_FORM_WORDS.get(form, form)}"))
    if cls:
        out.append(((flow, cls, ""), _CLASS_WORDS.get(cls, cls)))
    if form:
        out.append(((flow, "", form), f"{_FLOW_WORDS.get(flow, flow)} {_FORM_WORDS.get(form, form)}"))
    out.append(((flow, "", ""), _FLOW_WORDS.get(flow, flow)))
    return out


# #
# the table
# #

@dataclass(frozen=True)
class Run:
    """One lab run, as the table keeps it."""

    shape: str
    engine: str
    flow: str
    form: str
    cls: str
    passed: bool
    layers_pct: float | None = None
    cells: int | None = None
    seconds: float | None = None
    cells_across: float | None = None
    non_ortho: float | None = None

    @classmethod
    def from_row(cls, row: Mapping) -> Run | None:
        try:
            traits = ShapeTraits.from_dict(row.get("traits"))
            return cls(shape=str(row["shape"]), engine=str(row["engine"]),
                       flow=str(traits.flow or row.get("flow") or ""),
                       form=str(traits.form or row.get("form") or ""),
                       cls=shape_class(traits), passed=row.get("status") == "pass",
                       layers_pct=_num(row.get("layers_pct")), cells=_int(row.get("cells")),
                       seconds=_num(row.get("seconds")),
                       cells_across=_num(row.get("cells_across_p05")),
                       non_ortho=_num((row.get("quality") or {}).get("max_non_ortho")))
        except (KeyError, TypeError, ValueError):
            return None


def _num(v) -> float | None:
    return float(v) if isinstance(v, (int, float)) and not isinstance(v, bool) and math.isfinite(v) else None


def _int(v) -> int | None:
    n = _num(v)
    return int(n) if n is not None else None


@dataclass(frozen=True)
class Table:
    runs: tuple[Run, ...] = ()
    version: str = ""
    provenance: Mapping = field(default_factory=dict)

    @property
    def empty(self) -> bool:
        return not self.runs


def table_from(data: Mapping | None, *, exclude_shapes: Iterable[str] = ()) -> Table:
    """A table from its committed JSON (or any dict of the same shape). `exclude_shapes` drops
    every run on those shapes - how the held-out check builds a table that never saw them."""
    if not isinstance(data, Mapping):
        return Table()
    skip = set(exclude_shapes)
    runs = []
    if int(data.get("traits_version") or 0) not in (0, TRAITS_VERSION):
        logger.warning("fitness table: measured with traits v%s, this code measures v%s - "
                       "rebuild it (devtools/fitness/build_engine_fitness.py)",
                       data.get("traits_version"), TRAITS_VERSION)
    for row in data.get("rows") or ():
        if not isinstance(row, Mapping) or row.get("shape") in skip:
            continue
        r = Run.from_row(row)
        if r is not None:
            runs.append(r)
    return Table(runs=tuple(runs), version=str(data.get("version") or ""),
                 provenance=dict(data.get("provenance") or {}))


@lru_cache(maxsize=1)
def committed_table() -> Table:
    """The committed table, read once. A missing or unreadable file is an empty table: the
    recommendation then says it has no measured evidence, and nothing else changes."""
    try:
        return table_from(json.loads(TABLE_PATH.read_text(encoding="utf-8")))
    except (OSError, ValueError) as exc:
        logger.warning("fitness table unavailable (%s): engines are ranked without evidence", exc)
        return Table()


# #
# the evidence for one engine
# #

@dataclass(frozen=True)
class Evidence:
    """One engine's lab record for shapes like this one.

    The counts are QUOTED from the most specific level with runs on MIN_SHAPES distinct shapes
    (`level`, `words`); when a more specific level has a few runs but not that many shapes, those
    are kept too (`near_*`) so a reason can say both. The RATE the ranking reads comes from the
    most specific level with any runs, shrunk toward the next broader group: two failures on the
    only two thin gaps seen count, but only as much as two runs can."""

    runs: int = 0
    passed: int = 0
    shapes: int = 0
    level: int = -1             # 0 = the most specific level; -1 = no runs at all
    words: str = ""             # what "similar" meant at that level
    rate: float = 0.5           # the shrunk pass rate
    weight: float = PRIOR_RUNS  # runs behind that rate: the most specific level's, plus the prior
    layers_pct: float | None = None
    cells: int | None = None
    seconds: float | None = None
    cells_across: float | None = None
    non_ortho: float | None = None  # median max non-orthogonality (deg) of the passes
    per_form: bool = False      # the level fixes the file's form: one run per shape
    near_runs: int = 0          # the few runs at a more specific level than `level`
    near_passed: int = 0
    near_shapes: int = 0
    near_words: str = ""

    @property
    def low(self) -> bool:
        return self.level != 0 or self.shapes < MIN_SHAPES

    def as_dict(self) -> dict:
        d = {"runs": self.runs, "passed": self.passed, "shapes": self.shapes,
             "level": self.level, "similar": self.words, "rate": round(self.rate, 3),
             "layers_pct": None if self.layers_pct is None else round(self.layers_pct, 1),
             "cells": self.cells,
             "seconds": None if self.seconds is None else round(self.seconds, 1),
             "cells_across": None if self.cells_across is None else round(self.cells_across, 1),
             "max_non_ortho": None if self.non_ortho is None else round(self.non_ortho, 1),
             "low_evidence": self.low}
        if self.near_runs:
            d["near"] = {"runs": self.near_runs, "passed": self.near_passed,
                         "shapes": self.near_shapes, "similar": self.near_words}
        return d


def cautious(ev: Evidence) -> float:
    """The rate less CAUTION standard errors of it: what the ranking reads."""
    p = min(max(ev.rate, 0.0), 1.0)
    return max(0.0, p - CAUTION * math.sqrt(p * (1.0 - p) / max(ev.weight, 1.0)))


def _median(xs: Sequence[float]) -> float | None:
    return float(statistics.median(xs)) if xs else None


def _match(r: Run, key: tuple[str, str, str]) -> bool:
    flow, cls, form = key
    return r.flow == flow and (not cls or r.cls == cls) and (not form or r.form == form)


def evidence_for(table: Table, engine: str, *, flow: str, cls: str, form: str) -> Evidence:
    """The engine's evidence for a shape of this class and form (see Evidence)."""
    mine = [r for r in table.runs if r.engine == engine]
    stats = [(key, words, [r for r in mine if _match(r, key)])
             for key, words in _levels(flow, cls, form)]
    with_runs = [i for i, st in enumerate(stats) if st[2]]
    if not with_runs:
        return Evidence()
    # THE RATE: the most specific runs, plus PRIOR_RUNS pseudo runs at the (Laplace) rate of the
    # next broader group that holds more runs - each run counted once, never shrunk toward itself
    spec_rows = stats[with_runs[0]][2]
    # AN ENGINE NEVER TRIED ON THIS CLASS is read off its record on other shapes; how it does on
    # this kind is unknown, so that record is halved toward even odds and weighs no more than the
    # pseudo runs
    extrapolated = bool(cls) and not stats[with_runs[0]][0][1]
    weight = PRIOR_RUNS if extrapolated else len(spec_rows) + PRIOR_RUNS
    broader = next((st[2] for st in stats[with_runs[0] + 1:] if len(st[2]) > len(spec_rows)), [])
    prior = (sum(r.passed for r in broader) + 1.0) / (len(broader) + 2.0) if broader else 0.5
    rate = (sum(r.passed for r in spec_rows) + PRIOR_RUNS * prior) / (len(spec_rows) + PRIOR_RUNS)
    if extrapolated:
        # its record elsewhere counts as PRIOR_RUNS pseudo runs, and not knowing how this kind of
        # shape goes as PRIOR_RUNS more at even odds
        rate = (rate + 0.5) / 2.0
    quoted = next((i for i in with_runs if len({r.shape for r in stats[i][2]}) >= MIN_SHAPES),
                  with_runs[-1])
    key, words, rows = stats[quoted]
    ok = [r for r in rows if r.passed]
    near: dict[str, Any] = {}
    if with_runs[0] < quoted:
        _, nwords, nrows = stats[with_runs[0]]
        near = {"near_runs": len(nrows), "near_passed": sum(r.passed for r in nrows),
                "near_shapes": len({r.shape for r in nrows}), "near_words": nwords}
    return Evidence(
        runs=len(rows), passed=len(ok), shapes=len({r.shape for r in rows}), level=quoted,
        words=words, rate=rate, weight=weight,
        layers_pct=_median([r.layers_pct for r in ok if r.layers_pct is not None]),
        cells=_int(_median([r.cells for r in ok if r.cells is not None])),
        seconds=_median([r.seconds for r in ok if r.seconds is not None]),
        cells_across=_median([r.cells_across for r in ok if r.cells_across is not None]),
        non_ortho=_median([r.non_ortho for r in ok if r.non_ortho is not None]),
        per_form=bool(key[2]), **near)


# #
# the facts declared turf rows test (engines/home_turf.TURF_FACTS names every one)
# #

#: The cell budget assumed when the brief names none: the planner's usual ceiling.
DEFAULT_CELL_BUDGET = 2_000_000


def facts_of(traits: ShapeTraits, brief: Mapping | None = None) -> dict:
    """The facts an engine's home-turf rows test: the measured traits, the shape class, the cells
    a uniform mesh of the budget would put across the narrowest passage, and the brief's own facts
    (layers_requested, ground, cell_budget, region_count) when known. Unknown facts are left out,
    so a row about them says nothing."""
    d = {k: v for k, v in traits.as_dict().items() if v is not None and k != "notes"}
    d["shape_class"] = shape_class(traits)
    handles = handles_through_fluid(traits)
    if handles is not None:
        d["handles"] = handles
    extra = {k: v for k, v in dict(brief or {}).items() if v is not None}
    budget = extra.get("cell_budget") or DEFAULT_CELL_BUDGET
    if traits.narrow_vs_volume:
        try:
            d["cells_across_at_budget"] = round(traits.narrow_vs_volume * float(budget) ** (1.0 / 3.0), 2)
        except (TypeError, ValueError):
            pass
    d.update(extra)
    return d


def brief_facts(*, request_txt: str = "", review_brief_txt: str = "", patches=None,
                cell_budget=None, region_count=None) -> dict:
    """The turf facts a brief carries: whether it asks for near-wall layers (the fallback ladder's
    own reading), whether an external body stands on a declared ground wall, the cell budget and
    the region count. Only what can be read is returned."""
    out: dict = {}
    if (request_txt or "").strip() or (review_brief_txt or "").strip():
        from meshpipeline.pipeline.engine_fallback import layer_request
        out["layers_requested"] = bool(layer_request(request_txt or "", review_brief_txt or "").requested)
    if patches:
        try:
            from meshpipeline.engines.ground_plane import ground_patch_name
            out["ground"] = ground_patch_name(list(patches)) is not None
        except Exception:  # noqa: BLE001 - a fact we cannot read says nothing
            pass
    if isinstance(cell_budget, (int, float)) and not isinstance(cell_budget, bool) and cell_budget > 0:
        out["cell_budget"] = float(cell_budget)
    if isinstance(region_count, int) and not isinstance(region_count, bool):
        out["region_count"] = region_count
    return out


# #
# the recommendation
# #

@dataclass(frozen=True)
class EngineFit:
    engine: str
    label: str
    rank: int
    score: float
    evidence: Evidence
    reason: str
    recommended: bool = False
    turf: str = ""                            # the declared verdict: home | weak | outside | ''
    turf_words: tuple[str, ...] = ()
    layers: bool = True
    heads_up: str = ""                          # the declared weak spot (or limit) that holds here

    @property
    def outside(self) -> bool:
        return self.turf == "outside"

    def as_dict(self) -> dict:
        return {"engine": self.engine, "label": self.label, "rank": self.rank,
                "score": round(self.score, 3), "recommended": self.recommended,
                "outside": self.outside, "turf": self.turf, "turf_words": list(self.turf_words),
                "layers": self.layers, "reason": self.reason, "heads_up": self.heads_up,
                "fit": fit_words(self), "evidence": self.evidence.as_dict()}


@dataclass(frozen=True)
class Recommendation:
    engine: str
    reason: str
    fits: tuple[EngineFit, ...]
    shape: str
    traits: Mapping = field(default_factory=dict)
    table_version: str = ""

    @property
    def ranking(self) -> list[str]:
        return [f.engine for f in self.fits]

    def fit_of(self, engine: str) -> EngineFit | None:
        return next((f for f in self.fits if f.engine == engine), None)

    def as_dict(self) -> dict:
        return {"engine": self.engine, "reason": self.reason, "shape": self.shape,
                "fits": [f.as_dict() for f in self.fits], "traits": dict(self.traits),
                "table_version": self.table_version}


def ranking_of(data: Mapping | None) -> list[str]:
    """The ranking kept in a recommendation's dict (as a run's state carries it)."""
    if not isinstance(data, Mapping):
        return []
    return [str(f.get("engine")) for f in (data.get("fits") or ())
            if isinstance(f, Mapping) and f.get("engine")]


def fit_words(fit: EngineFit) -> str:
    """A couple of words for the fit, as the console shows them beside the engine."""
    if fit.outside:
        return "not suited"
    if fit.recommended:
        return "best fit"
    if fit.evidence.level < 0:
        return "untested"
    return "good fit" if fit.score >= 0.75 else "fair fit" if fit.score >= 0.45 else "poor fit"


def _label(engine: str) -> str:
    try:
        from meshpipeline.engines.registry import engine_label
        return engine_label(engine) or engine
    except Exception:  # noqa: BLE001 - a label never breaks advice
        return engine


def _spec(engine: str):
    try:
        from meshpipeline.engines.registry import get_spec
        return get_spec(engine)
    except Exception:  # noqa: BLE001
        return None


def _delivers_layers(spec) -> bool:
    dm = getattr(spec, "delivered_mesh", None)
    return bool(dm is None or dm.prism_layers)


def _minutes(seconds: float | None) -> str:
    if seconds is None:
        return ""
    if seconds < 90:
        return "about a minute a mesh"
    return f"about {int(round(seconds / 60.0))} minutes a mesh"


def _counted(passed: int, runs: int, shapes: int, words: str, *, per_form: bool) -> str:
    if per_form and runs == shapes:
        return f"passed {passed} of {shapes} similar shapes ({words})"
    return f"passed {passed} of {runs} tries on {shapes} similar shape{'s' if shapes != 1 else ''} ({words})"


def evidence_words(ev: Evidence) -> str:
    """The counts behind a fit, plainly: 'passed 9 of 10 similar shapes (...)', or what little
    there is on shapes exactly like this and the broader record the rest comes from."""
    if ev.level < 0:
        return "no lab results yet for shapes like this"
    broad = _counted(ev.passed, ev.runs, ev.shapes, ev.words, per_form=ev.per_form)
    if not ev.low:
        return broad
    if ev.near_runs:
        near = (f"passed {ev.near_passed} of {ev.near_runs} tries on {ev.near_shapes} "
                f"shape{'s' if ev.near_shapes != 1 else ''} like this ({ev.near_words})")
        return f"little evidence on shapes like this: {near}; {broad}"
    return f"no lab results on shapes exactly like this; {broad}"


def _reason(ev: Evidence, *, layers: bool) -> str:
    """One plain line: the evidence, the layers and the time."""
    parts = [evidence_words(ev)]
    if not layers:
        parts.append("no reliable near-wall layers")
    elif ev.layers_pct is not None and ev.passed:
        parts.append(f"near-wall layers on {ev.layers_pct:.0f}% of the wall")
    took = _minutes(ev.seconds)
    if took and ev.passed:
        parts.append(took)
    return "; ".join(p for p in parts if p)


def _heads_up(turf: str, words: Sequence[str]) -> str:
    """The engine's own declared words when its turf marks this case weak or outside."""
    if turf not in ("weak", "outside") or not words:
        return ""
    return str(words[0]).strip()


#: Within a tie on measured rate, a declared strength ranks first and a weak spot last.
_TURF_ORDER = {"home": 0, "": 1, "weak": 2, "outside": 3}


def recommend(traits: ShapeTraits, engines: Sequence[str], *, table: Table | None = None,
              brief: Mapping | None = None) -> Recommendation:
    """Rank `engines` - those that CAN take this file for this flow - for this geometry. The best
    measured engine that its own declared turf does not put OUTSIDE is recommended; every engine
    keeps its place on the list, with its reason, for the user to pick."""
    from meshpipeline.engines.home_turf import rows_for, verdict

    tab = committed_table() if table is None else table
    cls = shape_class(traits)
    facts = facts_of(traits, brief)
    wants_layers = bool(facts.get("layers_requested"))
    scored = []
    for name in dict.fromkeys(engines):
        ev = evidence_for(tab, name, flow=traits.flow, cls=cls, form=traits.form)
        spec = _spec(name)
        turf: str = ""
        words: tuple[str, ...] = ()
        if spec is not None and rows_for(spec, traits.flow):
            v = verdict(spec, traits.flow, facts)
            held = v.outside or v.weak_spots or v.strengths
            turf = v.severity if held else ""
            words = tuple(r.words for r in held)
        layers = _delivers_layers(spec)
        score = cautious(ev) * (NO_LAYERS_VALUE if wants_layers and not layers else 1.0)
        ladder = getattr(spec, "ladder_rank", 100) if spec is not None else 100
        scored.append((name, ev, turf, words, layers, score, ladder))

    def key(item):
        name, ev, turf, _, _, score, ladder = item
        return (turf == "outside", -math.floor(score / TIE_STEP + 1e-9), _TURF_ORDER.get(turf, 1),
                -(ev.layers_pct if ev.layers_pct is not None else -1.0),
                ev.seconds if ev.seconds is not None else math.inf, ladder, name)

    scored.sort(key=key)
    best = next((s[0] for s in scored if s[2] != "outside"), "")
    fits = tuple(EngineFit(engine=name, label=_label(name), rank=rank, score=score, evidence=ev,
                           reason=_reason(ev, layers=layers), recommended=name == best, turf=turf,
                           turf_words=words, layers=layers, heads_up=_heads_up(turf, words))
                 for rank, (name, ev, turf, words, layers, score, _) in enumerate(scored, start=1))
    top = next((f for f in fits if f.recommended), None)
    reason = top.reason if top is not None else ""
    return Recommendation(engine=best, reason=reason, fits=fits, shape=shape_words(traits),
                          traits=traits.as_dict(), table_version=tab.version)


def ranked_engines(order: Sequence[str], ranking: Sequence[str]) -> list[str]:
    """`order` (the declared ladder) re-ordered by a recommendation's ranking: ranked engines first,
    in ranking order, then the rest in their declared order. Only engines in `order` appear."""
    pos = {e: i for i, e in enumerate(ranking)}
    known = [e for e in order if e in pos]
    rest = [e for e in order if e not in pos]
    return sorted(known, key=lambda e: pos[e]) + rest


__all__ = ["BLUNT", "BRANCHED", "CAUTION", "CHAMBER", "DEFAULT_CELL_BUDGET", "MIN_SHAPES", "MULTI_REGION",
           "NO_LAYERS_VALUE", "OBSTACLES", "SLENDER", "TABLE_PATH", "THIN_GAP", "TUBE", "EngineFit", "Evidence",
           "Recommendation", "Run", "Table", "brief_facts", "cautious", "committed_table", "evidence_for",
           "evidence_words", "facts_of", "fit_words", "handles_through_fluid", "is_detailed",
           "ranked_engines", "ranking_of", "recommend", "shape_class", "shape_words", "table_from"]
