# Responsibility: Build consistent geometry sources, interpretations and materialised state for tests.
# Boundaries: test construction only; it mirrors the production contracts rather than reimplementing their rules.
from __future__ import annotations

import uuid
from dataclasses import dataclass
from pathlib import Path

from meshpipeline.contracts.geometry_source import (
    GeometryInterpretationRef,
    GeometrySourceRef,
    GeometryState,
    MaterializedGeometry,
    safe_suffix,
    sha256_of,
    source_object_key,
)
from meshpipeline.contracts.geometry_units import (
    GeometryInterpretation,
    LengthUnit,
    ResolutionBasis,
    scale_to_metres,
)

DEFAULT_SUFFIX = ".step"
DEFAULT_FILENAME = "part.step"


def geometry_bytes(marker: str = "canonical", size: int = 512) -> bytes:
    body = f"ISO-10303-21;/* {marker} */\n".encode()
    return body + b"0" * max(0, size - len(body))


def write_geometry(tmp_path: Path, *, marker: str = "canonical", size: int = 512,
                   filename: str = DEFAULT_FILENAME) -> Path:
    dest = Path(tmp_path) / filename
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(geometry_bytes(marker, size))
    return dest


def source_ref(*, source_id: str | None = None, owner_id: str = "owner-1",
               local_file: Path | None = None, tmp_path: Path | None = None,
               filename: str = DEFAULT_FILENAME, suffix_hint: str | None = None,
               marker: str = "canonical", size: int = 512,
               object_key: str | None = None, sha256: str | None = None,
               size_bytes: int | None = None) -> GeometrySourceRef:
    sid = source_id or str(uuid.uuid4())
    path = local_file
    if path is None and tmp_path is not None:
        path = write_geometry(tmp_path, marker=marker, size=size, filename=filename)
    if path is not None:
        real_digest, real_size = sha256_of(Path(path))
    else:
        # No file: derive a stable digest from generated bytes of the same shape.
        import hashlib
        payload = geometry_bytes(marker, size)
        real_digest, real_size = hashlib.sha256(payload).hexdigest(), len(payload)
    return GeometrySourceRef(
        source_id=sid,
        owner_id=owner_id,
        object_key=object_key or source_object_key(sid),
        sha256=sha256 or real_digest,
        size_bytes=real_size if size_bytes is None else size_bytes,
        original_filename=filename,
        suffix_hint=safe_suffix(suffix_hint if suffix_hint is not None
                                else Path(filename).suffix),
    )


def interpretation_ref(*, geometry_source_id: str,
                       interpretation_id: str | None = None,
                       unit: LengthUnit = LengthUnit.millimetre,
                       basis: ResolutionBasis = ResolutionBasis.user_confirmed,
                       scale: float | None = None,
                       evidence: str = "") -> GeometryInterpretationRef:
    return GeometryInterpretationRef(
        interpretation_id=interpretation_id or str(uuid.uuid4()),
        geometry_source_id=geometry_source_id, unit=unit.value,
        scale_to_metres=scale if scale is not None else scale_to_metres(unit),
        basis=basis.value, evidence=evidence)


def materialized(tmp_path: Path, **kwargs) -> MaterializedGeometry:
    filename = kwargs.get("filename", DEFAULT_FILENAME)
    unit = kwargs.pop("unit", LengthUnit.millimetre)
    basis = kwargs.pop("basis", ResolutionBasis.user_confirmed)
    interpretation = kwargs.pop("interpretation", None)
    local = write_geometry(tmp_path, marker=kwargs.get("marker", "canonical"),
                           size=kwargs.get("size", 512), filename=filename)
    ref = source_ref(local_file=local, tmp_path=None, **kwargs)
    return MaterializedGeometry(
        ref=ref,
        interpretation=interpretation or interpretation_ref(
            geometry_source_id=ref.source_id, unit=unit, basis=basis),
        local_path=local)


def geometry_state(tmp_path: Path, **kwargs) -> GeometryState:
    return materialized(tmp_path, **kwargs).to_state()


def stale_geometry_state(tmp_path: Path, *, stale_path: str = "/gone/other-process/source.step",
                         **kwargs) -> GeometryState:
    state = geometry_state(tmp_path, **kwargs)
    # the durable facts survive a checkpoint; only the path belongs to a process that is gone
    return GeometryState(ref=state["ref"], interpretation=state["interpretation"],
                         local_path=stale_path)


async def persisted_source(db, *, owner_id: str = "owner-1", tmp_path: Path | None = None,
                           filename: str = DEFAULT_FILENAME, marker: str = "canonical",
                           size: int = 512):
    import dataclasses

    from meshpipeline.persistence.repositories.geometry_source_repository import (
        GeometrySourceRepository,
    )

    ref = source_ref(owner_id=owner_id, tmp_path=tmp_path, filename=filename,
                     marker=marker, size=size)
    row = await GeometrySourceRepository().create(
        db, owner_id=ref.owner_id, original_filename=ref.original_filename,
        suffix_hint=ref.suffix_hint, object_key=ref.object_key, sha256=ref.sha256,
        size_bytes=ref.size_bytes)
    # The repository assigns the id, so the reference has to be rebuilt around the row's. Without
    # this the pair disagreed on identity: the returned ref named a source that was never
    # inserted, and any test binding it to a session hit a foreign key violation - or worse,
    # passed while describing a row that does not exist. The object key follows the id, as it does
    # at upload, so the two stay derivable from each other.
    row.object_key = source_object_key(row.id)
    await db.flush()
    return row, dataclasses.replace(ref, source_id=str(row.id), object_key=row.object_key)


def source_row(ref: GeometrySourceRef):
    from types import SimpleNamespace
    return SimpleNamespace(id=ref.source_id, owner_id=ref.owner_id, object_key=ref.object_key,
                           sha256=ref.sha256, size_bytes=ref.size_bytes,
                           original_filename=ref.original_filename, suffix_hint=ref.suffix_hint)


def source_lookup(ref: GeometrySourceRef | None):
    from unittest.mock import AsyncMock, patch

    async def _get_for_owner(_db, source_id, owner_id):
        if ref is None or str(source_id) != ref.source_id or str(owner_id) != ref.owner_id:
            return None
        return source_row(ref)

    return patch("meshpipeline.persistence.repositories.geometry_source_repository"
                 ".GeometrySourceRepository.get_for_owner", new=AsyncMock(side_effect=_get_for_owner))


def interpretation_lookup(ref, owner_id: str = "owner-1"):
    from unittest.mock import AsyncMock, patch

    from meshpipeline.contracts.geometry_units import (
        GeometryInterpretation,
        LengthUnit,
        ResolutionBasis,
    )

    async def _get_for_owner(_db, interpretation_id, asked_owner):
        if ref is None or str(interpretation_id) != ref.interpretation_id \
                or str(asked_owner) != owner_id:
            return None
        return GeometryInterpretation(
            interpretation_id=ref.interpretation_id, owner_id=owner_id,
            geometry_source_id=ref.geometry_source_id, unit=LengthUnit(ref.unit),
            scale_to_metres=float(ref.scale_to_metres),
            basis=ResolutionBasis(ref.basis), evidence=ref.evidence)

    return patch("meshpipeline.persistence.repositories.geometry_interpretation_repository"
                 ".GeometryInterpretationRepository.get_for_owner",
                 new=AsyncMock(side_effect=_get_for_owner))


# persisted, scale-resolved geometry

@dataclass(frozen=True)
class PersistedGeometry:

    ref: GeometrySourceRef
    interpretation: GeometryInterpretation
    local_path: Path
    payload: bytes

    @property
    def source_id(self) -> str:
        return self.ref.source_id

    @property
    def owner_id(self) -> str:
        return self.ref.owner_id

    @property
    def interpretation_id(self) -> str:
        return self.interpretation.interpretation_id

    @property
    def interpretation_snapshot(self) -> GeometryInterpretationRef:
        return GeometryInterpretationRef.from_domain(self.interpretation)

    def handle(self) -> MaterializedGeometry:
        return MaterializedGeometry(ref=self.ref, interpretation=self.interpretation_snapshot,
                                    local_path=self.local_path)

    def state(self) -> GeometryState:
        return self.handle().to_state()


async def persisted_geometry(db, *, unit: LengthUnit, basis: ResolutionBasis,
                             store=None, owner_id: str = "owner-1", tmp_path: Path | None = None,
                             filename: str = DEFAULT_FILENAME, marker: str = "canonical",
                             size: int = 512, evidence: str = "") -> PersistedGeometry:
    from meshpipeline.contracts.object_storage import get_object_store
    from meshpipeline.persistence.repositories.geometry_interpretation_repository import (
        GeometryInterpretationRepository,
    )
    from meshpipeline.persistence.repositories.geometry_source_repository import (
        GeometrySourceRepository,
    )

    if tmp_path is None:
        raise TypeError("persisted_geometry needs a tmp_path to write the source bytes into")

    # The id is chosen first because the object key DERIVES from it - the order production's
    # upload handler uses, so the key/row relationship a test exercises is the real one.
    source_id = uuid.uuid4()
    object_key = source_object_key(source_id)
    local = write_geometry(Path(tmp_path), marker=marker, size=size, filename=filename)
    digest, byte_size = sha256_of(local)

    (store or get_object_store()).upload_file(local_path=local, object_key=object_key)

    row = await GeometrySourceRepository().create(
        db, owner_id=owner_id, original_filename=filename,
        suffix_hint=safe_suffix(Path(filename).suffix), object_key=object_key,
        sha256=digest, size_bytes=byte_size)

    interpretation = await GeometryInterpretationRepository().record(
        db, owner_id=owner_id, geometry_source_id=row.id, unit=unit, basis=basis,
        evidence=evidence)
    await db.commit()

    return PersistedGeometry(
        ref=GeometrySourceRef(
            source_id=str(row.id), owner_id=owner_id, object_key=object_key, sha256=digest,
            size_bytes=byte_size, original_filename=filename,
            suffix_hint=safe_suffix(Path(filename).suffix)),
        interpretation=interpretation,
        local_path=local,
        payload=local.read_bytes(),
    )


def prepared_surface(path, *, unit: LengthUnit = LengthUnit.metre,
                     basis: ResolutionBasis = ResolutionBasis.user_confirmed,
                     source_id: str | None = None, interpretation_id: str | None = None,
                     from_occ: bool = False):
    from meshpipeline.cad.prepared_surface import PreparedSurface
    from meshpipeline.contracts.coordinate_state import from_occ_transfer, from_source_file

    interpretation = GeometryInterpretation(
        interpretation_id=interpretation_id or str(uuid.uuid4()),
        owner_id="owner-1",
        geometry_source_id=source_id or str(uuid.uuid4()),
        unit=unit, scale_to_metres=scale_to_metres(unit), basis=basis)
    consumed = (from_occ_transfer(interpretation) if from_occ
                else from_source_file(interpretation))
    return PreparedSurface(
        path=Path(path),
        source_id=interpretation.geometry_source_id,
        interpretation_id=interpretation.interpretation_id,
        consumed=consumed)
