/**
 * GENERATED from the contacts database: companies already on the outreach
 * list, mapped into prospecting segments. YC members are reassigned to the
 * yc segment via companies.yc.json. Audit tags ride in `audit`.
 */

export interface ExistingCompany {
  name: string;
  domain: string;
  people: number;
  roles: string;
  /** CAUTION / YC-batch note, empty if clean. */
  audit?: string;
}

export const EXISTING: Record<string, ExistingCompany[]> = {
  "hvac-thermal": [
    {"name": "2CRSi", "domain": "2crsi.com", "people": 2, "roles": "Other"},
    {"name": "Accelsius", "domain": "accelsius.com", "people": 2, "roles": "Other,CTO / Chief Engineer"},
    {"name": "Actiflow", "domain": "actiflow.com", "people": 1, "roles": "Other"},
    {"name": "Advanced Thermal Solutions (ATS)", "domain": "qats.com", "people": 4, "roles": "Other,Founder / CEO"},
    {"name": "Aira", "domain": "airahome.com", "people": 4, "roles": "Founder / CEO,Other"},
    {"name": "Asperitas", "domain": "asperitas.com", "people": 2, "roles": "Other,CTO / Chief Engineer"},
    {"name": "AtmosZero", "domain": "atmoszero.energy", "people": 3, "roles": "CTO / Chief Engineer,Founder / CEO"},
    {"name": "Barocal", "domain": "barocal.com", "people": 5, "roles": "Other"},
    {"name": "Blue Frontier", "domain": "bluefrontierac.com", "people": 2, "roles": "CTO / Chief Engineer,Engineering lead"},
    {"name": "BroadTech Engineering", "domain": "broadtechengineering.com", "people": 1, "roles": "Other"},
    {"name": "Calyos", "domain": "calyos-tm.com", "people": 3, "roles": "Founder / CEO,Other"},
    {"name": "Carrar", "domain": "carrar.net", "people": 1, "roles": "Founder / CEO"},
    {"name": "Celsia", "domain": "celsiainc.com", "people": 1, "roles": "CTO / Chief Engineer"},
    {"name": "Conflux Technology", "domain": "confluxtechnology.com", "people": 2, "roles": "Founder / CEO,Other"},
    {"name": "CPP Wind Engineering Consultants", "domain": "cppwind.com", "people": 2, "roles": "Founder / CEO,Other"},
    {"name": "Degree Controls (DegreeC)", "domain": "degreec.com", "people": 3, "roles": "Other"},
    {"name": "enevo", "domain": "enevo.co.uk", "people": 3, "roles": "Other"},
    {"name": "Engineering CFD", "domain": "engineeringcfd.co.uk", "people": 2, "roles": "Other,Aero / Simulation"},
    {"name": "Exoès", "domain": "exoes.com", "people": 5, "roles": "Other,Aero / Simulation"},
    {"name": "Green Revolution Cooling (GRC)", "domain": "grcooling.com", "people": 2, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Hypertec", "domain": "hypertec.com", "people": 3, "roles": "Other,Engineering lead"},
    {"name": "Ionetic", "domain": "ionetic.com", "people": 2, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Magnotherm", "domain": "magnotherm.com", "people": 4, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Predictive Engineering", "domain": "predictiveengineering.com", "people": 1, "roles": "Other"},
    {"name": "Quilt", "domain": "quilt.com", "people": 3, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "RWDI", "domain": "rwdi.com", "people": 5, "roles": "Other"},
    {"name": "Submer", "domain": "submer.com", "people": 3, "roles": "Founder / CEO"},
    {"name": "TEMISTh", "domain": "temisth.com", "people": 3, "roles": "Founder / CEO,Other"},
    {"name": "Transaera", "domain": "transaera.com", "people": 3, "roles": "CTO / Chief Engineer,Founder / CEO,Engineering lead"},
    {"name": "Ventiva", "domain": "ventiva.com", "people": 2, "roles": "Founder / CEO,Other"},
    {"name": "Wacker Ingenieure", "domain": "wacker-ingenieure.de", "people": 2, "roles": "Other"},
    {"name": "Wakefield Thermal", "domain": "wakefieldthermal.com", "people": 3, "roles": "Other,Engineering lead"},
    {"name": "xMEMS Labs", "domain": "xmems.com", "people": 3, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "ZutaCore", "domain": "zutacore.com", "people": 2, "roles": "Founder / CEO,Engineering lead"},
  ],
  "medical": [
    {"name": "4RealSim", "domain": "4realsim.com", "people": 1, "roles": "Other"},
    {"name": "4WEB Medical", "domain": "4webmedical.com", "people": 5, "roles": "Other"},
    {"name": "Adsilico", "domain": "adsilico.uk", "people": 3, "roles": "Founder / CEO,Aero / Simulation"},
    {"name": "Anteris Technologies", "domain": "anteristech.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "BiVACOR", "domain": "bivacor.com", "people": 3, "roles": "CTO / Chief Engineer,Engineering lead"},
    {"name": "Cardiawave", "domain": "cardiawave.com", "people": 5, "roles": "Other,Engineering lead"},
    {"name": "Continuum Blue", "domain": "continuum-blue.com", "people": 1, "roles": "Other"},
    {"name": "Corin Group", "domain": "coringroup.com", "people": 5, "roles": "Other"},
    {"name": "CorWave", "domain": "corwave.com", "people": 3, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "CroíValve", "domain": "croivalve.com", "people": 2, "roles": "Founder / CEO"},
    {"name": "Device Analytics", "domain": "deviceanalytics.com", "people": 1, "roles": "Other"},
    {"name": "Fluid Biomed", "domain": "fluidbiomed.com", "people": 1, "roles": "Engineering lead"},
    {"name": "Fluidda", "domain": "fluidda.com", "people": 3, "roles": "Other,Aero / Simulation"},
    {"name": "Foldax", "domain": "foldax.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Formus Labs", "domain": "formus.com", "people": 2, "roles": "Founder / CEO,Engineering lead"},
    {"name": "HighLife Medical", "domain": "highlifemedical.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "inHEART", "domain": "inheartmedical.com", "people": 1, "roles": "CTO / Chief Engineer"},
    {"name": "Laplace Interventional", "domain": "laplaceint.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Magenta Medical", "domain": "magentamed.com", "people": 4, "roles": "Founder / CEO,Engineering lead"},
    {"name": "Novostia", "domain": "novostia.com", "people": 5, "roles": "Founder / CEO,Other"},
    {"name": "Oxford Endovascular", "domain": "oxfordendovascular.com", "people": 2, "roles": "Other"},
    {"name": "Oxford Heartbeat", "domain": "oxfordheartbeat.com", "people": 2, "roles": "Other"},
    {"name": "PrediSurge", "domain": "predisurge.com", "people": 2, "roles": "CTO / Chief Engineer,Other"},
    {"name": "Procyrion", "domain": "procyrion.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Puzzle Medical Devices", "domain": "puzzlemed.com", "people": 3, "roles": "Founder / CEO,Engineering lead"},
    {"name": "restor3d", "domain": "restor3d.com", "people": 2, "roles": "Founder / CEO,Other"},
    {"name": "Sim&Cure", "domain": "sim-and-cure.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Simq GmbH", "domain": "simq.de", "people": 2, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "StarFish Medical", "domain": "starfishmedical.com", "people": 5, "roles": "Other"},
    {"name": "Supira Medical", "domain": "supiramedical.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Team Consulting", "domain": "team-consulting.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "TRiCares", "domain": "tricares.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "VDyne", "domain": "vdyne.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Vektor Medical", "domain": "vektormedical.com", "people": 2, "roles": "Founder / CEO,Other"},
    {"name": "Veryst Engineering", "domain": "veryst.com", "people": 5, "roles": "Other"},
    {"name": "Xeltis", "domain": "xeltis.com", "people": 5, "roles": "Other"},
  ],
  "auto": [
    {"name": "Adden Energy", "domain": "addenenergy.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "ADESS", "domain": "adess-ag.com", "people": 5, "roles": "Other"},
    {"name": "Advanced Electric Machines", "domain": "advancedelectricmachines.com", "people": 2, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Aerotak", "domain": "aerotak.com", "people": 1, "roles": "Aero / Simulation"},
    {"name": "Aeva Technologies", "domain": "aeva.ai", "people": 1, "roles": "Founder / CEO"},
    {"name": "Airflow Sciences Corporation", "domain": "airflowsciences.com", "people": 1, "roles": "Other"},
    {"name": "Alcon Components", "domain": "alcon.co.uk", "people": 5, "roles": "Other,CTO / Chief Engineer,Engineering lead"},
    {"name": "Aptera Motors", "domain": "aptera.us", "people": 6, "roles": "Founder / CEO,CTO / Chief Engineer,Engineering lead,Other", "audit": "CAUTION: Alive (EPA cert, first 40 production bodies ordered) but shrunk to ~57 employees and still needs $40-45M to fund initial production — fragile target."},
    {"name": "Bcomp", "domain": "bcomp.com", "people": 2, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Blue Current", "domain": "bluecurrent.com", "people": 5, "roles": "Founder / CEO,Other,CTO / Chief Engineer"},
    {"name": "Catesby Projects", "domain": "catesbyprojects.com", "people": 1, "roles": "Aero / Simulation"},
    {"name": "Cosworth", "domain": "cosworth.com", "people": 2, "roles": "Other"},
    {"name": "Czinger Vehicles", "domain": "czinger.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Dallara", "domain": "dallara.it", "people": 3, "roles": "Founder / CEO,Other"},
    {"name": "DeepDrive", "domain": "deepdrive.tech", "people": 5, "roles": "Founder / CEO"},
    {"name": "Drive System Design", "domain": "drivesystemdesign.com", "people": 5, "roles": "Other,Engineering lead,CTO / Chief Engineer"},
    {"name": "Einride", "domain": "einride.tech", "people": 1, "roles": "Founder / CEO"},
    {"name": "Electreon", "domain": "electreon.com", "people": 3, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Equipmake", "domain": "equipmake.com", "people": 3, "roles": "Other"},
    {"name": "Everrati", "domain": "everrati.com", "people": 3, "roles": "Founder / CEO,Engineering lead"},
    {"name": "Factorial Energy", "domain": "factorialenergy.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Forsee Power", "domain": "forseepower.com", "people": 6, "roles": "Founder / CEO,Other", "audit": "CAUTION: Operating but in financial turnaround: €15M of 2026 debt deferred to 2027, capital raise, REPOWER27 restructuring plan — tool spend likely frozen."},
    {"name": "Gibson Technology", "domain": "gibsontech.co.uk", "people": 2, "roles": "CTO / Chief Engineer,Engineering lead"},
    {"name": "Ginetta", "domain": "ginetta.com", "people": 2, "roles": "Other"},
    {"name": "Gordon Murray Automotive", "domain": "gordonmurrayautomotive.com", "people": 1, "roles": "Founder / CEO", "audit": "CAUTION: Acquired by Halo Cars Dec 2025 and CEO departed Nov 2025; company continues but the founder/CEO contact on file is likely stale post-acquisition."},
    {"name": "GreenGT", "domain": "greengt.ch", "people": 1, "roles": "Founder / CEO"},
    {"name": "Group14 Technologies", "domain": "group14.technology", "people": 6, "roles": "Founder / CEO,Engineering lead,Other,CTO / Chief Engineer"},
    {"name": "Harbinger Motors", "domain": "harbingermotors.com", "people": 6, "roles": "Founder / CEO,CTO / Chief Engineer,Other"},
    {"name": "Ilmor Engineering", "domain": "ilmor.com", "people": 4, "roles": "Other,Founder / CEO"},
    {"name": "Innoviz Technologies", "domain": "innoviz.tech", "people": 1, "roles": "Founder / CEO"},
    {"name": "Ion Storage Systems", "domain": "ionstoragesystems.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "JAS Motorsport", "domain": "jasmotorsport.com", "people": 1, "roles": "Other"},
    {"name": "Koenigsegg Automotive", "domain": "koenigsegg.com", "people": 6, "roles": "Founder / CEO,Other,Engineering lead"},
    {"name": "Lightship RV", "domain": "lightshiprv.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Lyten Inc", "domain": "lyten.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "M-Sport", "domain": "m-sport.co.uk", "people": 3, "roles": "Other,CTO / Chief Engineer"},
    {"name": "McMurtry Automotive", "domain": "mcmurtry.com", "people": 2, "roles": "Other"},
    {"name": "Microlino (Micro Mobility Systems)", "domain": "microlino-car.com", "people": 3, "roles": "Founder / CEO"},
    {"name": "Monumo", "domain": "monumo.ai", "people": 1, "roles": "Founder / CEO"},
    {"name": "Orange EV", "domain": "orangeev.com", "people": 4, "roles": "Founder / CEO,Engineering lead"},
    {"name": "Oreca", "domain": "oreca.com", "people": 1, "roles": "Other"},
    {"name": "Prodrive", "domain": "prodrive.com", "people": 4, "roles": "Engineering lead,Other"},
    {"name": "Rimac Technology", "domain": "rimac-technology.com", "people": 4, "roles": "Founder / CEO,Other"},
    {"name": "RML Group", "domain": "rmlgroup.com", "people": 2, "roles": "Founder / CEO,Other"},
    {"name": "Sabe Fluid Dynamics", "domain": "sabe.tech", "people": 2, "roles": "Founder / CEO,Engineering lead"},
    {"name": "Sila Nanotechnologies", "domain": "silanano.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "SiLC Technologies", "domain": "silc.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Slate Auto", "domain": "slate.auto", "people": 6, "roles": "Founder / CEO,Other,CTO / Chief Engineer,Engineering lead"},
    {"name": "Spark Racing Technology", "domain": "sparkracingtechnology.com", "people": 6, "roles": "Founder / CEO,Engineering lead,Other"},
    {"name": "Stark Future", "domain": "starkfuture.com", "people": 5, "roles": "CTO / Chief Engineer,Founder / CEO"},
    {"name": "Trackhouse Racing", "domain": "trackhouse.com", "people": 5, "roles": "Founder / CEO,Other"},
    {"name": "Verge Motorcycles", "domain": "vergemotorcycles.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "VFluid Advanced Tech", "domain": "vfluid.tech", "people": 2, "roles": "Founder / CEO,Aero / Simulation"},
    {"name": "White Motorcycle Concepts", "domain": "whitemotorcycleconcepts.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "WiTricity", "domain": "witricity.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Xos Trucks", "domain": "xostrucks.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Xtrac", "domain": "xtrac.com", "people": 2, "roles": "Other,Engineering lead"},
    {"name": "Zenvo Automotive", "domain": "zenvoautomotive.com", "people": 5, "roles": "Founder / CEO,Other"},
  ],
  "aero": [
    {"name": "Agile Space Industries", "domain": "agilespaceindustries.com", "people": 2, "roles": "Other,Engineering lead"},
    {"name": "Agnikul Cosmos", "domain": "agnikul.in", "people": 2, "roles": "Founder / CEO"},
    {"name": "Airbound", "domain": "airbound.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Allen Control Systems", "domain": "allencontrolsystems.com", "people": 6, "roles": "Founder / CEO,CTO / Chief Engineer,Engineering lead"},
    {"name": "Ampaire", "domain": "ampaire.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "AMSL Aero", "domain": "amslaero.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Anduril Industries", "domain": "anduril.com", "people": 7, "roles": "Founder / CEO,Engineering lead,CTO / Chief Engineer"},
    {"name": "Archer Aviation", "domain": "archer.com", "people": 7, "roles": "CTO / Chief Engineer,Aero / Simulation,Founder / CEO,Other"},
    {"name": "Astroscale Holdings", "domain": "astroscale.com", "people": 5, "roles": "Founder / CEO,Other,CTO / Chief Engineer"},
    {"name": "Astroscale Holdings", "domain": "astroscale.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Atmos Space Cargo", "domain": "atmos-space-cargo.com", "people": 3, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Aura Aero", "domain": "aura-aero.com", "people": 4, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Aurora Propulsion Technologies", "domain": "aurorapt.fi", "people": 1, "roles": "Founder / CEO"},
    {"name": "Bellatrix Aerospace", "domain": "bellatrix.aero", "people": 3, "roles": "Other"},
    {"name": "Benchmark Space Systems", "domain": "benchmarkspacesystems.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Beta Technologies", "domain": "beta.team", "people": 6, "roles": "Engineering lead,Other"},
    {"name": "Castelion", "domain": "castelion.com", "people": 4, "roles": "Founder / CEO,CTO / Chief Engineer,Engineering lead"},
    {"name": "CHAOS Industries", "domain": "chaosinc.com", "people": 6, "roles": "Founder / CEO,CTO / Chief Engineer,Other"},
    {"name": "ClearSpace SA", "domain": "clearspace.today", "people": 1, "roles": "Founder / CEO"},
    {"name": "Cranfield Aerospace Solutions", "domain": "cranfieldaerospace.com", "people": 2, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Cummings Aerospace", "domain": "cummingsaerospace.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "D-Orbit", "domain": "dorbit.space", "people": 1, "roles": "Founder / CEO"},
    {"name": "Dawn Aerospace", "domain": "dawnaerospace.com", "people": 6, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Destinus", "domain": "destinus.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Dronamics", "domain": "dronamics.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Electra.aero", "domain": "electra.aero", "people": 7, "roles": "Founder / CEO,Engineering lead,Other,CTO / Chief Engineer"},
    {"name": "Elroy Air", "domain": "elroyair.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Elysian Aircraft", "domain": "elysianaircraft.com", "people": 2, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Enpulsion", "domain": "enpulsion.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Epirus", "domain": "epirusinc.com", "people": 6, "roles": "Founder / CEO,Other,CTO / Chief Engineer,Engineering lead"},
    {"name": "Exotrail", "domain": "exotrail.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Firehawk Aerospace", "domain": "firehawkdefense.com", "people": 7, "roles": "Founder / CEO,CTO / Chief Engineer,Aero / Simulation,Engineering lead"},
    {"name": "Firestorm Labs", "domain": "launchfirestorm.com", "people": 2, "roles": "Founder / CEO,Engineering lead"},
    {"name": "Fleet Space Technologies", "domain": "fleetspace.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Flying Whales", "domain": "flying-whales.com", "people": 3, "roles": "Founder / CEO,Other"},
    {"name": "Gilmour Space Technologies", "domain": "gspace.com", "people": 5, "roles": "Founder / CEO,Other,CTO / Chief Engineer"},
    {"name": "Gilmour Space Technologies", "domain": "gspace.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "GITAI", "domain": "gitai.tech", "people": 1, "roles": "Founder / CEO"},
    {"name": "Gravitics", "domain": "gravitics.com", "people": 2, "roles": "Founder / CEO"},
    {"name": "Hadrian", "domain": "hadrian.co", "people": 1, "roles": "Founder / CEO"},
    {"name": "Hermeus", "domain": "hermeus.com", "people": 4, "roles": "Founder / CEO,CTO / Chief Engineer,Engineering lead"},
    {"name": "HyImpulse Technologies", "domain": "hyimpulse.de", "people": 1, "roles": "CTO / Chief Engineer"},
    {"name": "Hypersonix Launch Systems", "domain": "hypersonix.com", "people": 3, "roles": "CTO / Chief Engineer,Other,Engineering lead"},
    {"name": "HyPrSpace", "domain": "hypr-space.com", "people": 3, "roles": "Founder / CEO"},
    {"name": "Impulse Space", "domain": "impulsespace.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Isar Aerospace", "domain": "isaraerospace.com", "people": 4, "roles": "CTO / Chief Engineer,Founder / CEO"},
    {"name": "Isar Aerospace", "domain": "isaraerospace.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Jetoptera", "domain": "jetoptera.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "JetZero", "domain": "jetzero.aero", "people": 1, "roles": "CTO / Chief Engineer"},
    {"name": "Joby Aviation", "domain": "jobyaviation.com", "people": 3, "roles": "Founder / CEO,Aero / Simulation,Engineering lead"},
    {"name": "Jump Aero", "domain": "jumpaero.com", "people": 3, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "K2 Space", "domain": "k2space.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Lift Aircraft", "domain": "liftaircraft.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Loft Orbital", "domain": "loftorbital.com", "people": 5, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Mach Industries", "domain": "machindustries.com", "people": 6, "roles": "Founder / CEO,Other"},
    {"name": "Machina Labs", "domain": "machinalabs.ai", "people": 2, "roles": "Founder / CEO"},
    {"name": "Magdrive", "domain": "magdrive.space", "people": 1, "roles": "CTO / Chief Engineer"},
    {"name": "Morpheus Space", "domain": "morpheus-space.com", "people": 5, "roles": "CTO / Chief Engineer,Founder / CEO"},
    {"name": "Morpheus Space", "domain": "morpheus-space.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Muon Space", "domain": "muonspace.com", "people": 4, "roles": "Engineering lead,CTO / Chief Engineer,Founder / CEO"},
    {"name": "Natilus", "domain": "natilus.co", "people": 1, "roles": "Founder / CEO"},
    {"name": "Navier", "domain": "navierboat.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "New Frontier Aerospace", "domain": "nfaero.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Orbex", "domain": "orbex.space", "people": 5, "roles": "Other,Aero / Simulation"},
    {"name": "Orbex", "domain": "orbex.space", "people": 1, "roles": "Founder / CEO"},
    {"name": "Orbion Space Technology", "domain": "orbionspace.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Overland AI", "domain": "overland.ai", "people": 1, "roles": "Founder / CEO", "audit": "CAUTION: Primarily an off-road autonomy software company (OverDrive stack); it does now productionize the Ultra UGV, so some structural work exists, but aero/thermal meshing pain is thin."},
    {"name": "Pale Blue", "domain": "pale-blue.co.jp", "people": 3, "roles": "Founder / CEO"},
    {"name": "Pangea Propulsion", "domain": "pangeapropulsion.com", "people": 1, "roles": "Founder / CEO", "audit": " (was Pangea Aerospace)"},
    {"name": "Phantom Space", "domain": "phantomspace.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Piasecki Aircraft", "domain": "piasecki.com", "people": 2, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Pixxel", "domain": "pixxel.space", "people": 1, "roles": "Founder / CEO"},
    {"name": "PLD Space", "domain": "pldspace.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "POLARIS Raumflugzeuge", "domain": "polaris-raumflugzeuge.de", "people": 1, "roles": "Founder / CEO"},
    {"name": "Portal Space Systems", "domain": "portalsystems.space", "people": 1, "roles": "Founder / CEO"},
    {"name": "Quantum Systems", "domain": "quantum-systems.com", "people": 5, "roles": "Founder / CEO,Other"},
    {"name": "Quantum Systems", "domain": "quantum-systems.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Radia Inc", "domain": "radia.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Radian Aerospace", "domain": "radianaerospace.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Reaction Dynamics", "domain": "reactiondynamics.space", "people": 1, "roles": "CTO / Chief Engineer"},
    {"name": "Reliable Robotics", "domain": "reliable.co", "people": 1, "roles": "Founder / CEO", "audit": "CAUTION: Retrofits certified Cessna Caravans with autonomy; engineering is avionics/certification software with minimal new-airframe CFD/FEA. Borderline fit."},
    {"name": "Revolution Space", "domain": "revolutionspace.com", "people": 1, "roles": "Founder / CEO", "audit": " (was Accion Systems)"},
    {"name": "Rocket Factory Augsburg", "domain": "rfa.space", "people": 1, "roles": "CTO / Chief Engineer"},
    {"name": "Rocket Lab", "domain": "rocketlabcorp.com", "people": 4, "roles": "Aero / Simulation,Founder / CEO,CTO / Chief Engineer,Other"},
    {"name": "Rotor Technologies", "domain": "rotor.ai", "people": 1, "roles": "Founder / CEO"},
    {"name": "Sabrewing Aircraft", "domain": "sabrewingaircraft.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Saildrone", "domain": "saildrone.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Saronic Technologies", "domain": "saronic.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Shield AI", "domain": "shield.ai", "people": 5, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "SkyDrive Inc", "domain": "skydrive2020.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Space Forge", "domain": "spaceforge.co.uk", "people": 1, "roles": "Founder / CEO"},
    {"name": "Starfish Space", "domain": "starfishspace.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Stark", "domain": "stark-defence.com", "people": 2, "roles": "Founder / CEO,Other"},
    {"name": "Stratolaunch", "domain": "stratolaunch.com", "people": 6, "roles": "Founder / CEO,Engineering lead,Other,CTO / Chief Engineer", "audit": "CAUTION: Duplicate of the 'Stratolaunch' row (identical domain and contact profile) — dedupe before sending or the CEO gets emailed twice."},
    {"name": "Stratolaunch", "domain": "stratolaunch.com", "people": 1, "roles": "Founder / CEO", "audit": "CAUTION: Duplicate of the 'Stratolaunch' row (identical domain and contact profile) — dedupe before sending or the CEO gets emailed twice."},
    {"name": "Supernal (Hyundai)", "domain": "supernal.aero", "people": 1, "roles": "Founder / CEO", "audit": "CAUTION: S-A2 development paused Sept 2025 after CEO/CTO departures; ~80% of staff (296 people) laid off Feb 2026, skeleton crew of 70-80 remains. Alive but the worst possible moment for tooling outreach."},
    {"name": "T-Minus Engineering", "domain": "t-minus.nl", "people": 3, "roles": "Founder / CEO"},
    {"name": "The Exploration Company", "domain": "exploration.space", "people": 5, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "ThrustMe", "domain": "thrustme.fr", "people": 1, "roles": "Founder / CEO"},
    {"name": "Tiberius Aerospace", "domain": "tiberius.com", "people": 5, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "True Anomaly", "domain": "trueanomaly.space", "people": 6, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Type One Energy", "domain": "typeoneenergy.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "TYTAN Technologies", "domain": "tytan-technologies.com", "people": 3, "roles": "CTO / Chief Engineer,Founder / CEO"},
    {"name": "Ursa Major", "domain": "ursamajor.com", "people": 6, "roles": "Founder / CEO,Aero / Simulation,Other,CTO / Chief Engineer"},
    {"name": "Varda Space", "domain": "varda.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Vast", "domain": "vast.space", "people": 6, "roles": "Founder / CEO,Other,CTO / Chief Engineer,Engineering lead"},
    {"name": "Velo3D", "domain": "velo3d.com", "people": 1, "roles": "Founder / CEO", "audit": "CAUTION: 95% acquired by Arrayed Additive in a Jan 2025 debt-for-equity restructuring after near-collapse; CEO/board replaced. Also an AM-printer vendor, not an airframe/engine designer, so the pitch fits poorly."},
    {"name": "Venturi Astrolab", "domain": "astrolab.space", "people": 5, "roles": "Other"},
    {"name": "Venus Aerospace", "domain": "venusaero.com", "people": 2, "roles": "Founder / CEO,Engineering lead"},
    {"name": "Whisper Aero", "domain": "whisper.aero", "people": 2, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Windracers", "domain": "windracers.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Wisk Aero", "domain": "wisk.aero", "people": 2, "roles": "Aero / Simulation,Founder / CEO", "audit": "CAUTION: Wholly owned Boeing subsidiary since mid-2023; the aero/simulation team is real, but tool adoption likely routes through Boeing procurement rather than a startup-style trial."},
  ],
  "consultancies": [
    {"name": "Aerotherm", "domain": "aerotherm.co.za", "people": 1, "roles": "Other"},
    {"name": "AltaSim Technologies", "domain": "altasimtechnologies.com", "people": 2, "roles": "Founder / CEO,Other"},
    {"name": "ATA Engineering", "domain": "ata-e.com", "people": 5, "roles": "Other"},
    {"name": "CFD Direct", "domain": "cfd.direct", "people": 2, "roles": "Founder / CEO"},
    {"name": "CFD Engine", "domain": "cfdengine.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "CFD Research Corporation", "domain": "cfd-research.com", "people": 2, "roles": "Founder / CEO"},
    {"name": "Combustion Science and Engineering", "domain": "csefire.com", "people": 5, "roles": "Other"},
    {"name": "Desanco", "domain": "desanco.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "DOCAN", "domain": "docanco.com", "people": 5, "roles": "Other"},
    {"name": "EnginSoft USA", "domain": "enginsoftusa.com", "people": 1, "roles": "Other"},
    {"name": "FEAmax", "domain": "feamax.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Femto Engineering", "domain": "femto.eu", "people": 5, "roles": "Other"},
    {"name": "Gradient Wind Engineering", "domain": "gradientwind.com", "people": 5, "roles": "Other,Aero / Simulation"},
    {"name": "LEAP Australia", "domain": "leapaust.com.au", "people": 3, "roles": "Other"},
    {"name": "Megagenix", "domain": "megagenix.com.sg", "people": 1, "roles": "Other"},
    {"name": "Merkle CAE Solutions", "domain": "merkle-cae.de", "people": 1, "roles": "Other"},
    {"name": "MR-CFD", "domain": "mr-cfd.com", "people": 1, "roles": "Other"},
    {"name": "Navier Flow Consultants", "domain": "navier-flow-consultants.com", "people": 2, "roles": "Other,Aero / Simulation"},
    {"name": "NING Research", "domain": "ningresearch.sg", "people": 4, "roles": "Other,Aero / Simulation"},
    {"name": "Ozen Engineering", "domain": "ozeninc.com", "people": 1, "roles": "Engineering lead"},
    {"name": "Quest Consultants", "domain": "questconsult.com", "people": 1, "roles": "Other"},
    {"name": "Resolved Analytics", "domain": "resolvedanalytics.com", "people": 3, "roles": "Aero / Simulation,Other"},
    {"name": "Stress Engineering Services", "domain": "stress.com", "people": 1, "roles": "CTO / Chief Engineer"},
    {"name": "Synthetik Applied Technologies", "domain": "synthetik-technologies.com", "people": 1, "roles": "Other"},
    {"name": "TotalSim", "domain": "totalsim.us", "people": 1, "roles": "Founder / CEO"},
    {"name": "Tridiagonal Solutions", "domain": "tridiagonal.com", "people": 5, "roles": "Other,Aero / Simulation"},
    {"name": "Upstream CFD", "domain": "upstream-cfd.com", "people": 1, "roles": "Aero / Simulation"},
    {"name": "Xi Engineering Consultants", "domain": "xiengineering.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Zeus Numerix", "domain": "zeusnumerix.com", "people": 1, "roles": "Other"},
  ],
  "energy": [
    {"name": "Aalo Atomics", "domain": "aalo.com", "people": 2, "roles": "CTO / Chief Engineer,Engineering lead"},
    {"name": "Antora Energy", "domain": "antora.com", "people": 2, "roles": "Founder / CEO"},
    {"name": "Barber-Nichols", "domain": "barber-nichols.com", "people": 3, "roles": "Engineering lead,CTO / Chief Engineer"},
    {"name": "CalWave Power Technologies", "domain": "calwave.energy", "people": 4, "roles": "CTO / Chief Engineer,Engineering lead,Other"},
    {"name": "Carbon Clean", "domain": "carbonclean.com", "people": 4, "roles": "Founder / CEO,Engineering lead"},
    {"name": "Celeroton", "domain": "celeroton.com", "people": 1, "roles": "CTO / Chief Engineer"},
    {"name": "Climeworks", "domain": "climeworks.com", "people": 4, "roles": "Founder / CEO,Other,Engineering lead"},
    {"name": "Commonwealth Fusion Systems", "domain": "cfs.energy", "people": 3, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Copenhagen Atomics", "domain": "copenhagenatomics.com", "people": 1, "roles": "CTO / Chief Engineer"},
    {"name": "CorPower Ocean", "domain": "corpowerocean.com", "people": 1, "roles": "CTO / Chief Engineer"},
    {"name": "Echogen Power Systems", "domain": "echogen.com", "people": 3, "roles": "Founder / CEO,Engineering lead,CTO / Chief Engineer"},
    {"name": "Electric Hydrogen", "domain": "eh2.com", "people": 5, "roles": "CTO / Chief Engineer,Founder / CEO,Engineering lead"},
    {"name": "First Light Fusion", "domain": "firstlightfusion.com", "people": 2, "roles": "Other,Engineering lead"},
    {"name": "Focused Energy", "domain": "focused-energy.co", "people": 1, "roles": "Founder / CEO"},
    {"name": "General Fusion", "domain": "generalfusion.com", "people": 3, "roles": "CTO / Chief Engineer,Founder / CEO,Other"},
    {"name": "Highview Power", "domain": "highviewpower.com", "people": 1, "roles": "Other"},
    {"name": "Hysata", "domain": "hysata.com", "people": 3, "roles": "Founder / CEO,Other,CTO / Chief Engineer"},
    {"name": "Kairos Power", "domain": "kairospower.com", "people": 3, "roles": "Founder / CEO,Other,CTO / Chief Engineer"},
    {"name": "Kitemill", "domain": "kitemill.com", "people": 2, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Kitepower", "domain": "thekitepower.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Kyoto Fusioneering", "domain": "kyotofusioneering.com", "people": 5, "roles": "Other,Founder / CEO"},
    {"name": "Mocean Energy", "domain": "mocean.energy", "people": 2, "roles": "Founder / CEO,Other"},
    {"name": "newcleo", "domain": "newcleo.com", "people": 5, "roles": "Founder / CEO,Other"},
    {"name": "Orbital Marine Power", "domain": "orbitalmarine.com", "people": 2, "roles": "Founder / CEO,Other"},
    {"name": "PCA Engineers", "domain": "pcaeng.co.uk", "people": 2, "roles": "Engineering lead,Other"},
    {"name": "Peregrine Turbine Technologies", "domain": "peregrineturbine.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Proxima Fusion", "domain": "proximafusion.com", "people": 5, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Quaise Energy", "domain": "quaise.com", "people": 2, "roles": "Other,Engineering lead"},
    {"name": "Radiant (Radiant Industries)", "domain": "radiantnuclear.com", "people": 2, "roles": "Other,Engineering lead"},
    {"name": "Rondo Energy", "domain": "rondo.com", "people": 2, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Sunfire", "domain": "sunfire.de", "people": 5, "roles": "Founder / CEO,Other,CTO / Chief Engineer,Engineering lead"},
    {"name": "Svante Technologies", "domain": "svanteinc.com", "people": 5, "roles": "Founder / CEO,Other"},
    {"name": "TAE Technologies", "domain": "tae.com", "people": 4, "roles": "Founder / CEO,Other"},
    {"name": "Terrestrial Energy", "domain": "terrestrialenergy.com", "people": 3, "roles": "Founder / CEO,CTO / Chief Engineer,Other"},
    {"name": "Thea Energy", "domain": "thea.energy", "people": 3, "roles": "Founder / CEO,CTO / Chief Engineer,Engineering lead"},
    {"name": "Tokamak Energy", "domain": "tokamakenergy.com", "people": 4, "roles": "Founder / CEO,Other,CTO / Chief Engineer"},
    {"name": "Verdagy", "domain": "verdagy.com", "people": 4, "roles": "Other,Engineering lead,CTO / Chief Engineer"},
    {"name": "X-energy", "domain": "x-energy.com", "people": 5, "roles": "Other,Engineering lead,CTO / Chief Engineer"},
    {"name": "Zap Energy", "domain": "zapenergy.com", "people": 5, "roles": "Founder / CEO,Other,CTO / Chief Engineer,Engineering lead"},
  ],
  "yc": [
    {"name": "Aerones", "domain": "aerones.com", "people": 5, "roles": "Founder / CEO,Other"},
    {"name": "Airhart Aeronautics", "domain": "airhartaero.com", "people": 1, "roles": "Founder / CEO", "audit": "[YC S22]"},
    {"name": "AirMyne", "domain": "airmyne.com", "people": 5, "roles": "Founder / CEO,Other,Engineering lead"},
    {"name": "Albacore Inc.", "domain": "albacore.inc", "people": 5, "roles": "Founder / CEO,Other"},
    {"name": "Beyond Aero", "domain": "beyond-aero.com", "people": 1, "roles": "CTO / Chief Engineer", "audit": "[YC W22]"},
    {"name": "Boom Supersonic", "domain": "boomsupersonic.com", "people": 1, "roles": "Founder / CEO", "audit": "[YC W16]"},
    {"name": "Illuminant Surgical", "domain": "illuminant.ai", "people": 2, "roles": "Founder / CEO,Other"},
    {"name": "Inversion Space", "domain": "inversionspace.com", "people": 1, "roles": "Founder / CEO", "audit": "[YC S21]"},
    {"name": "Odys Aviation", "domain": "odysaviation.com", "people": 1, "roles": "Founder / CEO", "audit": "[YC S21]"},
    {"name": "Orbital Operations", "domain": "orbitalops.tech", "people": 1, "roles": "Founder / CEO", "audit": "[YC W25]"},
    {"name": "REGENT Craft", "domain": "regentcraft.com", "people": 2, "roles": "CTO / Chief Engineer,Founder / CEO", "audit": "[YC W21]"},
    {"name": "Relativity Space", "domain": "relativityspace.com", "people": 1, "roles": "Founder / CEO", "audit": "[YC W16]"},
    {"name": "Remora", "domain": "remoracarbon.com", "people": 5, "roles": "Founder / CEO,Engineering lead,Other"},
    {"name": "Seaflight Technologies", "domain": "seaflight.tech", "people": 1, "roles": "Founder / CEO", "audit": "[YC S22]"},
    {"name": "Stoke Space", "domain": "stokespace.com", "people": 1, "roles": "Founder / CEO", "audit": "[YC W21]"},
    {"name": "TransAstra", "domain": "transastra.com", "people": 1, "roles": "Founder / CEO", "audit": "[YC S21]"},
    {"name": "Velontra", "domain": "velontra.com", "people": 1, "roles": "CTO / Chief Engineer", "audit": "[YC S22]"},
    {"name": "Zipline International", "domain": "flyzipline.com", "people": 4, "roles": "CTO / Chief Engineer,Founder / CEO,Other", "audit": "[YC S14]"},
    {"name": "Zipline International", "domain": "flyzipline.com", "people": 1, "roles": "Founder / CEO", "audit": "[YC S14]"},
  ],
  "semiconductors": [
    {"name": "Akhetonics", "domain": "akhetonics.com", "people": 3, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Atomica (MEMS Foundry)", "domain": "atomica.com", "people": 3, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Axelera AI", "domain": "axelera.ai", "people": 4, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Ayar Labs", "domain": "ayarlabs.com", "people": 4, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Blaize", "domain": "blaize.com", "people": 5, "roles": "Founder / CEO,CTO / Chief Engineer,Engineering lead"},
    {"name": "Cambridge GaN Devices", "domain": "camgandevices.com", "people": 6, "roles": "Founder / CEO,Other"},
    {"name": "Cerebras Systems", "domain": "cerebras.net", "people": 5, "roles": "Founder / CEO"},
    {"name": "CoolIT Systems", "domain": "coolitsystems.com", "people": 5, "roles": "Founder / CEO,Other,Engineering lead,CTO / Chief Engineer"},
    {"name": "Corintis", "domain": "corintis.com", "people": 3, "roles": "Founder / CEO"},
    {"name": "d-Matrix", "domain": "d-matrix.ai", "people": 6, "roles": "Founder / CEO,CTO / Chief Engineer,Engineering lead,Other"},
    {"name": "Eliyan", "domain": "eliyan.com", "people": 3, "roles": "Founder / CEO,Engineering lead", "audit": "CAUTION: Primarily licenses die-to-die PHY interconnect IP — meshing pain is doubtful, though their chiplet/packaging test silicon gives a thin thermal-simulation angle."},
    {"name": "Eridan Communications", "domain": "eridan.io", "people": 6, "roles": "Founder / CEO,CTO / Chief Engineer,Other"},
    {"name": "Fabric8Labs", "domain": "fabric8labs.com", "people": 3, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Frore Systems", "domain": "froresystems.com", "people": 5, "roles": "Founder / CEO,CTO / Chief Engineer,Engineering lead"},
    {"name": "Groq", "domain": "groq.com", "people": 3, "roles": "Founder / CEO,Other"},
    {"name": "Hailo Technologies", "domain": "hailo.ai", "people": 3, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Iceotope Technologies", "domain": "iceotope.com", "people": 3, "roles": "Founder / CEO,Other,Engineering lead"},
    {"name": "Kneron", "domain": "kneron.com", "people": 3, "roles": "Founder / CEO,Engineering lead"},
    {"name": "Lightmatter", "domain": "lightmatter.ai", "people": 4, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Multibeam Corporation", "domain": "multibeamcorp.com", "people": 4, "roles": "Founder / CEO,Engineering lead,Other"},
    {"name": "Mythic AI", "domain": "mythic.ai", "people": 3, "roles": "Founder / CEO,Engineering lead"},
    {"name": "Paragraf", "domain": "paragraf.com", "people": 6, "roles": "Founder / CEO,Other"},
    {"name": "Phononic Devices", "domain": "phononic.com", "people": 6, "roles": "Founder / CEO,Other"},
    {"name": "Picocom", "domain": "picocom.com", "people": 3, "roles": "Founder / CEO,Other"},
    {"name": "PsiQuantum", "domain": "psiquantum.com", "people": 4, "roles": "Founder / CEO,Other"},
    {"name": "Ranovus", "domain": "ranovus.com", "people": 4, "roles": "Founder / CEO,Engineering lead"},
    {"name": "Syenta", "domain": "syenta.com", "people": 6, "roles": "Founder / CEO,CTO / Chief Engineer,Other,Engineering lead"},
    {"name": "Tenstorrent", "domain": "tenstorrent.com", "people": 6, "roles": "Founder / CEO,Engineering lead"},
    {"name": "Teramount", "domain": "teramount.com", "people": 3, "roles": "Founder / CEO,Engineering lead"},
    {"name": "VisIC Technologies", "domain": "visic-tech.com", "people": 3, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Xanadu Quantum Technologies", "domain": "xanadu.ai", "people": 2, "roles": "Founder / CEO"},
  ],
  "marine": [
    {"name": "Anemoi Marine Technologies", "domain": "anemoimarine.com", "people": 2, "roles": "Other"},
    {"name": "Arc", "domain": "arcboats.com", "people": 2, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Artemis Technologies", "domain": "artemistechnologies.co.uk", "people": 5, "roles": "Founder / CEO,Other,CTO / Chief Engineer,Aero / Simulation"},
    {"name": "BAR Technologies", "domain": "bartechnologies.uk", "people": 3, "roles": "Founder / CEO,CTO / Chief Engineer,Engineering lead"},
    {"name": "Blue Water Autonomy", "domain": "blw.ai", "people": 3, "roles": "CTO / Chief Engineer,Founder / CEO"},
    {"name": "bound4blue", "domain": "bound4blue.com", "people": 2, "roles": "Founder / CEO,Aero / Simulation"},
    {"name": "C-Job Naval Architects", "domain": "c-job.com", "people": 3, "roles": "Other,CTO / Chief Engineer"},
    {"name": "Candela", "domain": "candela.com", "people": 3, "roles": "Founder / CEO,Other"},
    {"name": "Cape Horn Engineering", "domain": "cape-horn-eng.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Cellula Robotics", "domain": "cellula.com", "people": 2, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Chartwell Marine", "domain": "chartwellmarine.com", "people": 2, "roles": "Other"},
    {"name": "CJR Propulsion", "domain": "cjrprop.com", "people": 1, "roles": "Other"},
    {"name": "Dykstra Naval Architects", "domain": "dykstra-na.nl", "people": 3, "roles": "Other"},
    {"name": "Glosten", "domain": "glosten.com", "people": 2, "roles": "Other"},
    {"name": "GSea Design", "domain": "gseadesign.com", "people": 2, "roles": "Other"},
    {"name": "HamiltonJet", "domain": "hamiltonjet.com", "people": 3, "roles": "Other"},
    {"name": "HavocAI", "domain": "havocai.com", "people": 3, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Hull Vane BV", "domain": "hullvane.com", "people": 1, "roles": "Other"},
    {"name": "Incat Crowther", "domain": "incatcrowther.com", "people": 4, "roles": "Other"},
    {"name": "International Submarine Engineering", "domain": "ise.bc.ca", "people": 3, "roles": "Founder / CEO,Other"},
    {"name": "KNUD E. HANSEN", "domain": "knudehansen.com", "people": 2, "roles": "Other"},
    {"name": "Maritime Robotics", "domain": "maritimerobotics.com", "people": 5, "roles": "Other"},
    {"name": "MMG (Mecklenburger Metallguss)", "domain": "mecklenburger-metallguss.com", "people": 1, "roles": "Other"},
    {"name": "Mocean Offshore", "domain": "mocean-offshore.com", "people": 1, "roles": "Founder / CEO"},
    {"name": "Ocean Aero", "domain": "oceanaero.com", "people": 3, "roles": "Other,CTO / Chief Engineer,Engineering lead"},
    {"name": "Robert Allan Ltd", "domain": "ral.ca", "people": 1, "roles": "CTO / Chief Engineer"},
    {"name": "Seasats", "domain": "seasats.com", "people": 3, "roles": "CTO / Chief Engineer,Founder / CEO"},
    {"name": "Silverstream Technologies", "domain": "silverstream-tech.com", "people": 5, "roles": "Other"},
    {"name": "Temporary Works Design (TWD)", "domain": "twd.nl", "people": 5, "roles": "Founder / CEO,Other,Engineering lead"},
    {"name": "U-Boat Worx", "domain": "uboatworx.com", "people": 4, "roles": "Founder / CEO,Engineering lead"},
    {"name": "Ulstein Group", "domain": "ulstein.com", "people": 5, "roles": "Other"},
    {"name": "Van Oossanen Naval Architects", "domain": "oossanen.nl", "people": 1, "roles": "Other"},
    {"name": "Vatn Systems", "domain": "vatn.com", "people": 3, "roles": "Founder / CEO,CTO / Chief Engineer"},
    {"name": "Vessev", "domain": "vessev.com", "people": 1, "roles": "Founder / CEO"},
  ],
};
